---
- name: Converge
  hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3
    girder_virtualenv: "{{ ansible_user_dir }}/.venvs/girder"

  pre_tasks:
    - name: Install python prereqs
      apt:
        name:
          - python3-venv
          - python3-dev
        update_cache: true
      become: true

    - name: Create virtualenv
      command: |
        /usr/bin/python3.6 -m venv "{{ girder_virtualenv }}"
      args:
        creates: "{{ girder_virtualenv }}"

    - name: Install mongo
      apt:
        name: mongodb-server
      become: true

  roles:
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_vhosts:
        - listen: "80"
          server_name: "girder"
          extra_parameters: |
            location / {
              proxy_set_header Host $proxy_host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_pass http://localhost:8888/;
              # Must set the following for SSE notifications to work
              proxy_buffering off;
              proxy_cache off;
              proxy_set_header Connection '';
              proxy_http_version 1.1;
              chunked_transfer_encoding off;
              proxy_read_timeout 600s;
              proxy_send_timeout 600s;
            }
      become: true

    - role: ansible-role-girder

  post_tasks:
    - name: Set Girder to run on port 8888
      ini_file:
        dest: "/etc/girder.cfg"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - section: "global"
          option: "server.socket_port"
          value: "8888"
        - section: "global"
          option: "tools.proxy.on"
          value: "True"
        - section: "server"
          option: "mode"
          value: '"production"'
      become: true
      notify: Restart Girder
