---
- name: Prepare
  hosts: targets
  pre_tasks:
    # gpg is needed to add other APT repositories
    - name: Install gnupg2
      apt:
        update_cache: true
        name: gnupg2
        state: present
        force_apt_get: true
      become: true
      become_user: root
  roles:
    - role: girder.girder
      vars:
        girder_database_uri: "mongodb://mongodb:27017/girder"
        girder_web: false
