---
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    privileged: false
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
    security_opts:
      - seccomp=unconfined
    networks:
      - name: molecule
    groups:
      - targets
  - name: mongodb
    image: mongo:4.4
    pre_build_image: true
    override_command: false
    networks:
      - name: molecule
    groups:
      - services
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # Defining this here, instead of in playbooks, also ensures it's picked
        # up by Testinfra
        ansible_python_interpreter: "/usr/bin/python3"
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: testinfra
  options:
    hosts: targets
