---
- name: Converge
  hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    girder_virtualenv: "{{ ansible_user_dir }}/.venvs/girder"

  pre_tasks:
    - name: Install python prereqs
      apt:
        name:
          - python3-venv
          - python3-setuptools
          - python3-dev
      become: true
      become_user: root

    - name: Create virtualenv
      command: |
        /usr/bin/python3.6 -m venv "{{ girder_virtualenv }}"
      args:
        creates: "{{ girder_virtualenv }}"

  roles:
    - role: girder.mongodb

    - role: ansible-role-girder
